baseURL = "https://m91profile.pages.dev/"
title = "田中 美帆のオフィシャルサイト"

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
  
[pagination]
 pagerSize = 10

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  env = "production"
  description = "大阪大学医学系研究科保健学専攻｜公衆衛生看護｜研究者プロフィール、研究、論文、ニュース"
  author = "田中 美帆"
  ShowShareButtons = false
  ShowReadingTime = false
  ShowBreadCrumbs = true
  defaultTheme = "auto"

[params.label]
  text = "Miho Tanaka"
  icon = "/uploads/portrait.jpg"
  iconHeight = 34

[params.banner]
image = "/img/project-banner.png"  
url   = "https://researchmap.jp/miho_1991" 
alt   = "researchmap"           
position = "before"  

[languages.ja.params.banner]
image = "/img/project-banner.png"
url = "https://researchmap.jp/miho_1991"
alt = "researchmap"
position = "before"

[[params.socialIcons]]
  name = "orcid"
  url  = "https://orcid.org/0009-0006-6039-9625"
[[params.socialIcons]]
  name = "facebook"
  url  = "https://www.facebook.com/miho.phn"
[[params.socialIcons]]
  name = "instagram"
  url  = "https://www.instagram.com/m91office/"

[languages]

  [languages.ja]
    languageName = "日本語"
    weight = 1
    contentDir = "content/ja"
 
    [languages.ja.params.homeInfoParams]
      Title   = "田中美帆"
      Content = """大阪大学医学系研究科保健学専攻　助教  
    研究の歩みや日々の気づきも発信中、アイコンからどうぞ"""
   
    [languages.ja.menu]
      [[languages.ja.menu.main]]
        name = "プロフィール"
        url = "/about/"
        weight = 1
      [[languages.ja.menu.main]]
        name = "研究"
        url = "/research/"
        weight = 2
      [[languages.ja.menu.main]]
        name = "論文"
        url = "/publications/"
        weight = 3
      [[languages.ja.menu.main]]
        name = "連絡先"
        url = "/contact/"
        weight = 4
      [[languages.ja.menu.main]]
        name = "ニュース"
        url = "/news/"
        weight = 5
        
  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"
    [languages.en.params.homeInfoParams]
      Title = "Miho Tanaka"
      Content = "Osaka University — Division of Health Sciences "
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        url = "/about/"
        weight = 1
      [[languages.en.menu.main]]
        name = "Research"
        url = "/research/"
        weight = 2
      [[languages.en.menu.main]]
        name = "Publications"
        url = "/publications/"
        weight = 3
      [[languages.en.menu.main]]
        name = "News"
        url = "/news/"
        weight = 4
      [[languages.en.menu.main]]
        name = "Contact"
        url = "/contact/"
        weight = 5
